### ISSUE TITLE
AbstractAttributeStore should use the ArrayListMultiMap 

### ISSUE THREAD

**Issue by cjnolet** [calrissian/mango#194]
The problem is, the MultiMap interface was purposely made to not extend Serializable yet the Entity interface extends Serializable. By using the ArrayListMultimap implementation instead of the interface, this object once again becomes serializable.

**Comment by eawagner** [comment]
Interesting, I thought only the implementation needed to be serializable for the internal objects, but I guess it possibly make sense that Java would have to handle null objects.

I am ok with changing the internal class reference to ArrayListMultimap since we don't expose this directly anymore through the AttributeStore API, it won't have any external effect on the class other than when being introspected by things like Java serialization.  Just a little surprised as I have never come across this case before!

**Comment by eawagner** [comment]
Fixed
